nnoremap j gj
nnoremap k gk
nnoremap B ^
nnoremap E $
nnoremap ^ <nop>
nnoremap $ <nop>
set nowrap
set autoindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set nojoinspaces
set number
